import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { User, ArrowRight } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { supabase } from "@/lib/supabase";
import { useLanguage } from "@/lib/i18n";

export type Blog = {
  id: string;
  created_at: string;
  title: string;
  content: string;
  author: string;
  category: string;
  image_url?: string;
  read_time: string;
};

export const MOCK_BLOGS: Omit<Blog, "id" | "created_at">[] = [
  {
    title: "The Future of Ethical Fashion Sourcing in 2026: A Blueprint for Circular Production",
    content: `Introduction: The Paradigm Shift in Apparel Sourcing

As we navigate through 2026, the global fashion landscape is undergoing its most profound transformation since the Industrial Revolution. The traditional, linear "take-make-waste" model is being aggressively dismantled, replaced by a circular paradigm where transparency, accountability, and environmental restoration are the primary pillars of success. Sourcing executives are no longer evaluating factories based on cost-per-unit and lead times alone; instead, carbon footprints, fair-wage indexes, water-recycling capabilities, and materials traceability have taken center stage.

In this comprehensive blueprint, we outline the fundamental shifts defining ethical apparel manufacturing in 2026, and how forward-thinking fashion houses are positioning themselves for a sustainable future.

The Digital Product Passport (DPP) Mandate

One of the major drivers of circularity in 2026 is the widespread adoption of Digital Product Passports (DPPs). Backed by strict European Union regulations and growing consumer demand in North America and Asia, DPPs require brands to document every step of a garment's life cycle. 

From the organic cotton farms in the Gujarat region of India to the weaving mills of Osaka and the final assembly lines, every participant in the supply chain must upload verifiable data. Consumers can simply scan a QR code embedded in the garment's wash care label to trace:
1. The exact geographical coordinates where the raw fiber was harvested.
2. The specific chemical certifications of the dyes used.
3. The carbon equivalent footprint of the transport leg.
4. Detailed recycling instructions, including chemical composition for circular recycling hubs.

This level of transparency eliminates greenwashing overnight and forces factories to maintain impeccable standards to remain competitive.

Closed-Loop Production and Water-less Dyeing

Water conservation is the single most critical challenge in modern textile processing. Traditionally, dyeing a single ton of fabric could require up to 200 tons of fresh water, which was subsequently discharged as toxic effluent. In 2026, premium factories in our global network have implemented closed-loop filtration systems and revolutionary water-less dyeing technologies.

Using supercritical carbon dioxide (scCO2) or advanced digital spray-dyeing machines, manufacturers can now dye synthetic and natural fibers with zero water consumption and 95% dye absorption rates. Any chemical residues are captured, neutralized, and recycled within a sealed loop. 

Furthermore, circular manufacturing relies heavily on post-consumer waste. We are seeing a massive influx of chemically recycled nylon (like Econyl) and mechanical cotton recycling systems that allow brands to blend post-industrial scrap into new premium collections without compromising yarn strength or drape.

Fair Wages, Decentralized Audits, and Labor Ethics

Beyond environmental concerns, the "S" in ESG (Environmental, Social, and Governance) is receiving unprecedented scrutiny. Brands can no longer hide behind third-party auditing firms that conduct pre-scheduled, superficial annual inspections.

In 2026, ethical sourcing is powered by real-time worker feedback platforms and decentralized ledger technology. Workers can anonymously report working conditions, wage disbursements, and overtime hours via secure mobile interfaces. These data points are compiled and compared against local living wage benchmarks rather than bare-minimum legal standards. 

Factories that proactively implement fair-wage programs are seeing higher retention rates, lower defect rates, and a more dedicated workforce. Brands that partner with these ethical manufacturers enjoy stable production lines and protect their brand equity from reputational crises.

Strategic Regional Clusters and Near-Shoring

To combat the massive emissions generated by international shipping, fashion labels are reorganizing their networks into strategic regional clusters. Instead of spinning yarn in one continent, weaving it in another, and sewing it in a third, brands are looking for vertical clusters where all steps occur within a 100-mile radius.

Near-shoring is also growing rapidly. European brands are expanding their production footprints in Portugal and Turkey, while North American labels are partnering with advanced facilities in Mexico. These regional clusters allow for faster turnaround times (shifting from 6-month calendars to 3-week responsive cycles), reducing the need to maintain massive, speculative inventories that inevitably lead to unsold deadstock.

Conclusion: Sourcing for the Next Generation

Sourcing ethically in 2026 is not merely a marketing strategy or a compliance requirement—it is a survival mechanism. As resources grow scarcer and consumer values shift permanently toward environmental stewardship, the brands that thrive will be those that view their manufacturers not as disposable vendors, but as strategic partners in a closed-loop, regenerative ecosystem.`,
    author: "Elena Rostova",
    category: "Sustainability",
    image_url: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80",
    read_time: "10 min read"
  },
  {
    title: "Navigating Global Textile Supply Chains: A Brand's Guide to Logistics & Tariff Engineering",
    content: `Introduction: The New Era of Supply Chain Management

Managing a fashion brand's supply chain has always been a balancing act, but in 2026, the global geopolitical and environmental landscape has turned it into a complex, high-stakes game. Rising fuel costs, shipping lane congestion, and fluctuating trade tariffs mean that simple mistakes can destroy a label's profit margins.

For sourcing executives, success requires a shift from reactive logistics to proactive, resilient supply chain design. This guide details the essential strategies brands are using to navigate global shipping, mitigate risk, and optimize manufacturing footprints.

Decoupling Lead Times: The Buffer Stock Strategy

Historically, fashion operated on a "Just-In-Time" (JIT) model, aiming to receive materials exactly as production lines were ready to spin. However, shipping delays and border bottlenecks have made JIT highly risky.

In 2026, top fashion labels utilize a "buffer stock" strategy for core materials. By identifying fabrics and yarns that are used across multiple seasons and collections—such as organic pima cotton, high-grade linen, or recycled polyester—brands buy raw fibers in bulk during periods of low market demand. 

These raw materials are stored in secure warehouses near manufacturing hubs. When a design is finalized, the factory can immediately begin cutting and sewing, cutting down the development-to-shipping window by up to 45 days. This approach improves agility and protects brands from sudden price hikes in raw commodities.

Tariff Engineering and Rules of Origin

With global trade policies changing rapidly, tariff engineering has become an essential tool for sourcing teams. Tariff engineering involves designing products specifically to qualify for lower duties based on regional trade agreements.

For instance, by tweaking the fiber blend of a garment (e.g., adding 5% silk to a wool coat) or sourcing specific trims from a treaty-aligned nation, brands can qualify for duty-free status under agreements like the USMCA or EU-Vietnam FTA. 

Sourcing teams must work closely with designers and patternmakers early in the development cycle to ensure that:
1. Fiber compositions align with target tariff classifications.
2. The rules of origin are documented down to the raw spinning stage.
3. Component sourcing matches bilateral trade treaties.

This pre-planning can save brands millions of dollars annually in import duties, allowing them to maintain competitive retail pricing without squeezing design budgets.

Real-Time Transit Progress and Logistics Tech

Relying on estimated arrival times provided by ocean carriers is no longer sufficient. Modern supply chain operations rely on real-time visibility.

Through internet-of-things (IoT) GPS trackers attached to shipping containers, brands can monitor the precise coordinates, ambient temperature, and humidity of their cargo. If a vessel is rerouted or delayed at customs, logistics software automatically triggers alerts and adjusts production schedules at secondary factories.

Furthermore, integrating live customs API feeds allows customs brokers to file clearance documents days before the ship docks, reducing port dwell times from an average of nine days to under 24 hours.

Mitigating Factory Risk: The 70/30 Sourcing Rule

Relying on a single factory or region for all production is a major vulnerability. To build resilience, experienced brands implement the 70/30 sourcing rule.

Under this model, a brand allocates 70% of its volume to a primary, highly efficient factory (often in Asia or Central America) to take advantage of scale and cost efficiency. The remaining 30% is allocated to a secondary, near-shore factory closer to the brand's primary market (such as Portugal for Europe or Mexico for the US).

In the event of trade blockades, natural disasters, or labor strikes in the primary region, the near-shore factory has the capacity and patterns ready to scale up production immediately. This ensures that the brand's retail partners receive inventory, preventing costly stockouts during peak seasons.

Conclusion: Building a Resilient Supply Chain

Resilience is the ultimate currency in global logistics. Brands that build flexible networks, invest in visibility software, and design products with tariff considerations in mind will not only survive disruptions, but will establish a significant competitive advantage over competitors stuck in legacy, rigid systems.`,
    author: "Marcus Vance",
    category: "Supply Chain",
    image_url: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=800&q=80",
    read_time: "10 min read"
  },
  {
    title: "How AI is Revolutionizing Fashion Trend Forecasting: From Pixels to Production Line",
    content: `Introduction: Moving Beyond the Trend Forecaster's Intuition

For decades, fashion trend forecasting relied on editorial intuition, runway reviews, and street style photography. While this artistic approach defined the industry's aesthetic direction, it often resulted in huge discrepancies between forecast demands and actual consumer purchases—leading to billions of dollars of unsold inventory destroyed or sent to landfills every year.

In 2026, artificial intelligence has bridged the gap between creative design and manufacturing. By utilizing predictive analytics, machine learning, and real-time social listening, AI forecasting systems can predict color, fabric, and silhouette trends with up to 92% accuracy, allowing brands to design, source, and manufacture with confidence.

Social and Search Listening: Curation at Scale

The cycle of a trend has accelerated rapidly. Traditional forecasting agencies released books 18 months in advance, but today, a trend can go from viral social video to consumer demand in less than three weeks.

AI forecasting begins with search and social listening. Natural language processing (NLP) models monitor billions of daily data points across platforms like Instagram, TikTok, Pinterest, search engines, and e-commerce platforms. 

By tracking changes in visual attributes (colors, patterns, sleeve lengths, fabric textures) rather than just keyword text, the AI can detect emerging trends weeks before they enter mainstream media. The system tracks the rate of change: if search interest in "natural linen wrap skirts" rises by 15% week-over-week for three consecutive weeks among early-adopter demographics, the system alerts design and sourcing teams.

Predictive Production: Eliminating Deadstock

The most critical impact of AI forecasting is the elimination of speculative manufacturing. Historically, brands produced large runs of an item, hoping it would sell. In 2026, AI helps brands forecast exact unit demand by region.

By feeding historical sales data, local weather forecasts, economic indexes, and regional search trends into neural networks, the AI generates highly localized demand curves. A brand will know to allocate 1,200 units of a linen shirt in light blue to the UK market and 500 units of the same shirt in beige to the Japanese market, reducing unsold inventory and markdowns.

Furthermore, these predictive models feed directly into raw material pre-purchasing. Sourcing teams can buy fabric greige goods (undyed fabric base) months in advance and only apply dye and print runs once the AI confirms color demand ratios.

Algorithmic Color and Silhouette Formulation

AI isn't just counting keywords—it is actively helping design teams formulate collections. Generative design tools can analyze a brand's historical design elements and combine them with trending silhouetting parameters.

For example, a designer can prompt an AI tool to generate silhouettes that blend the brand's classic tailoring with the emerging "utility-wear" trend. Within seconds, the tool generates dozens of photorealistic flat drawings and 3D CAD renders. 

These renders are mapped directly to factory patterns, meaning that once a design is approved, the digital file can be sent straight to computerized fabric cutting machines. This cuts sampling cycles from several weeks to less than 48 hours.

Streamlining Raw Material Pre-Purchasing

Sourcing fabric is often the longest phase of fashion production. AI optimizes this by analyzing supplier capacity and raw material inventories in real time.

If the AI predicts an upcoming spike in demand for wool outerwear, the sourcing system automatically checks current wool stock levels across the brand's pre-approved supplier network. It flags potential capacity bottlenecks and suggests placing advance yarn reservations with factories in Italy or the UK before peak seasonal demand drives up prices.

This integration of forecasting and sourcing ensures that the design team's vision is backed by a fully prepared, cost-optimized supply chain.

Conclusion: The Fusion of Art and Algorithm

AI trend forecasting is not about replacing the human designer; it is about empowering them. By removing the guesswork from trend prediction and inventory allocation, AI allows creative directors to focus on craftsmanship, storytelling, and high-quality design, confident in the knowledge that their collections will find a market and leave a minimal environmental footprint.`,
    author: "Aria Chen",
    category: "Technology",
    image_url: "https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=800&q=80",
    read_time: "10 min read"
  }
];

export function Blogs() {
  const [blogs, setBlogs] = useState<Blog[]>([]);
  const [loading, setLoading] = useState(true);
  const { t } = useLanguage();

  const fetchBlogs = async () => {
    setLoading(true);
    try {
      // 1. Try Supabase with a 2-second timeout
      const query = supabase
        .from("blogs")
        .select("*")
        .order("created_at", { ascending: false });

      const timeout = new Promise<never>((_, reject) =>
        setTimeout(() => reject(new Error("Timeout")), 2000)
      );

      const { data, error } = await (Promise.race([query, timeout]) as Promise<any>);

      if (error) throw error;

      if (data && data.length > 0) {
        setBlogs(data);
      } else {
        // Table exists but is empty, fallback to LocalStorage
        loadFromLocalStorage();
      }
    } catch (err) {
      console.warn("Supabase blogs fetch failed or timed out, falling back to LocalStorage:", err);
      loadFromLocalStorage();
    } finally {
      setLoading(false);
    }
  };

  const loadFromLocalStorage = () => {
    try {
      const local = localStorage.getItem("maisone_blogs_v2");
      if (local) {
        setBlogs(JSON.parse(local));
      } else {
        // Seed initial sample blogs to LocalStorage if empty
        const seeded: Blog[] = MOCK_BLOGS.map((b, idx) => ({
          id: `local-blog-${idx}`,
          created_at: new Date(Date.now() - idx * 86400000).toISOString(),
          ...b
        }));
        localStorage.setItem("maisone_blogs_v2", JSON.stringify(seeded));
        setBlogs(seeded);
      }
    } catch (err) {
      console.error("Failed to load blogs from LocalStorage, resetting:", err);
      const seeded: Blog[] = MOCK_BLOGS.map((b, idx) => ({
        id: `local-blog-${idx}`,
        created_at: new Date(Date.now() - idx * 86400000).toISOString(),
        ...b
      }));
      localStorage.setItem("maisone_blogs_v2", JSON.stringify(seeded));
      setBlogs(seeded);
    }
  };

  useEffect(() => {
    fetchBlogs();
  }, []);

  return (
    <section id="blog" className="py-24 border-t border-white/5 relative overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-electric/5 to-transparent pointer-events-none opacity-40" />
      
      <div className="relative mx-auto max-w-7xl px-6">
        <div className="max-w-3xl mb-16">
          <p className="text-[10px] uppercase tracking-[0.3em] text-electric mb-6">{t("blogs.label")}</p>
          <h2 className="font-serif text-4xl sm:text-5xl tracking-tight mb-6">
            Maisone <span className="italic gradient-text font-serif">Journal</span>
          </h2>
          <p className="text-muted-foreground text-sm max-w-xl leading-relaxed">
            {t("blogs.headingHighlight")}
          </p>
        </div>

        {loading ? (
          <div className="grid md:grid-cols-3 gap-6">
            {[1, 2, 3].map((i) => (
              <div key={i} className="rounded-3xl border border-white/5 bg-white/[0.01] p-6 space-y-4 animate-pulse">
                <div className="aspect-[16/10] bg-white/5 rounded-2xl w-full" />
                <div className="h-4 bg-white/5 rounded w-1/3" />
                <div className="h-6 bg-white/5 rounded w-full" />
                <div className="h-4 bg-white/5 rounded w-full" />
              </div>
            ))}
          </div>
        ) : (
          <div className="grid md:grid-cols-3 gap-8">
            {blogs.map((blog) => (
              <motion.article
                key={blog.id}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                whileHover={{ y: -6 }}
                className="group rounded-3xl border border-white/5 bg-white/[0.01] overflow-hidden flex flex-col h-full hover:border-electric/30 hover:bg-white/[0.02] transition-all duration-300"
              >
                {blog.image_url && (
                  <div className="aspect-[16/10] overflow-hidden relative">
                    <img
                      src={blog.image_url}
                      alt={blog.title}
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                    />
                    <div className="absolute top-4 left-4">
                      <span className="text-[9px] uppercase tracking-widest font-semibold bg-black/85 backdrop-blur-sm border border-white/10 px-3 py-1 rounded-full text-electric">
                        {blog.category}
                      </span>
                    </div>
                  </div>
                )}
                <div className="p-6 flex-1 flex flex-col justify-between space-y-4">
                  <div className="space-y-3">
                    <div className="flex items-center gap-4 text-[10px] text-muted-foreground font-medium uppercase tracking-wider">
                      <span className="flex items-center gap-1.5 font-bold"><User className="size-3 text-electric/80" /> {blog.author}</span>
                      <span>•</span>
                      <span>{blog.read_time}</span>
                    </div>
                    <h3 className="font-serif text-xl sm:text-2xl text-white tracking-tight group-hover:text-electric transition-colors line-clamp-2">
                      {blog.title}
                    </h3>
                    <p className="text-xs text-muted-foreground/80 leading-relaxed line-clamp-3">
                      {blog.content}
                    </p>
                  </div>
                  <Link
                    to="/blog/$blogId"
                    params={{ blogId: blog.id }}
                    className="inline-flex items-center gap-1.5 text-xs font-semibold text-white group-hover:text-electric transition-colors cursor-pointer self-start"
                  >
                    {t("blogs.readArticle")} <ArrowRight className="size-3.5 group-hover:translate-x-1 transition-transform" />
                  </Link>
                </div>
              </motion.article>
            ))}
          </div>
        )}
      </div>
    </section>
  );
}
