import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { TrendingUp, Sparkles, Activity, Loader2 } from "lucide-react";
import { createServerFn } from "@tanstack/react-start";
import { supabase } from "@/lib/supabase";
import { useLanguage } from "@/lib/i18n";

export type Region = "Japan" | "United Kingdom" | "Europe" | "United States" | "India" | "China";

export type Forecast = {
  fabrics: { name: string; score: number; signal: string }[];
  colors: { name: string; hex: string; pantone: string; score: number }[];
  silhouettes: { name: string; score: number; note: string }[];
};

export const generateTrendForecastFn = createServerFn({ method: "POST" })
  .validator((d: { region: string; season: string }) => d)
  .handler(async ({ data }) => {
    const { region, season } = data;
    const apiKey = process.env.KIMI_API_KEY;
    const baseURL = process.env.KIMI_BASE_URL || "https://api.moonshot.cn/v1";
    const model = process.env.KIMI_MODEL || "moonshot-v1-8k";

    if (!apiKey) {
      throw new Error("Missing KIMI_API_KEY environment variable.");
    }

    const systemPrompt = `You are a professional fashion trend forecasting AI. Generate a realistic, trend-accurate fashion forecast for the region: "${region}" and the season: "${season}".

You must return ONLY a raw JSON object with the following exact typescript structure:
{
  "fabrics": [
    { "name": "Fabric Name", "score": 90, "signal": "Reason/signal of trend" }
  ],
  "colors": [
    { "name": "Color Name", "hex": "#HEXCOLOR", "pantone": "Pantone code", "score": 85 }
  ],
  "silhouettes": [
    { "name": "Silhouette Name", "score": 80, "note": "Brief style/season note" }
  ]
}

Provide exactly 4 fabrics, 4 colors (with valid CSS hex codes starting with '#' and matching Pantone formats), and 3 silhouettes. Do not include any markdown styling like \`\`\`json or explanation text. Output pure valid JSON.`;

    const response = await fetch(`${baseURL}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: `Generate fashion forecast for region "${region}" and season "${season}".` },
        ],
        temperature: 0.7,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`API call failed: ${errorText}`);
    }

    const result = await response.json();
    const content = result.choices?.[0]?.message?.content?.trim();
    if (!content) {
      throw new Error("No response content from AI model.");
    }

    let cleanJson = content;
    if (cleanJson.startsWith("```")) {
      cleanJson = cleanJson.replace(/^```json\s*/, "").replace(/```$/, "").trim();
    }

    try {
      const parsed = JSON.parse(cleanJson);
      if (!parsed.fabrics || !parsed.colors || !parsed.silhouettes) {
        throw new Error("Missing expected JSON properties.");
      }
      return parsed;
    } catch (e: any) {
      console.error("Failed to parse LLM JSON:", cleanJson);
      throw new Error(`Invalid JSON format generated by AI: ${e.message}`);
    }
  });

export const DEFAULT_DATA: Record<Region, Forecast> = {
  Japan: {
    fabrics: [
      { name: "Natural Indigo", score: 96, signal: "Okayama mills · capacity tight" },
      { name: "Sashiko Cotton", score: 89, signal: "Heritage revival" },
      { name: "Tech Linen", score: 82, signal: "Tokyo runway" },
      { name: "Wagara Jacquard", score: 74, signal: "Editorial" },
    ],
    colors: [
      { name: "Aizome Blue", hex: "#1a3a6b", pantone: "19-3953", score: 95 },
      { name: "Shironeri", hex: "#fbf7ee", pantone: "11-0103", score: 88 },
      { name: "Sumi Black", hex: "#1a1a1a", pantone: "19-4007", score: 82 },
      { name: "Beni Red", hex: "#c4302b", pantone: "18-1664", score: 71 },
    ],
    silhouettes: [
      { name: "Wide-leg Trouser", score: 91, note: "SS '26" },
      { name: "Haori Layer", score: 85, note: "Resort" },
      { name: "Boxy Workwear", score: 79, note: "Cross-season" },
    ],
  },
  "United Kingdom": {
    fabrics: [
      { name: "Heritage Tweed", score: 92, signal: "Savile Row revival" },
      { name: "Waxed Cotton", score: 86, signal: "Outerwear demand" },
      { name: "Fine Merino", score: 80, signal: "Knitwear sell-through" },
      { name: "Liberty Print", score: 72, signal: "Editorial" },
    ],
    colors: [
      { name: "Forest Loden", hex: "#2d4a2b", pantone: "19-0220", score: 90 },
      { name: "Oxblood", hex: "#5c1f1b", pantone: "19-1525", score: 85 },
      { name: "Stone Grey", hex: "#a8a39a", pantone: "16-1305", score: 78 },
      { name: "Royal Mustard", hex: "#c89a3a", pantone: "15-0942", score: 70 },
    ],
    silhouettes: [
      { name: "Tailored Coat", score: 90, note: "FW '26" },
      { name: "Field Jacket", score: 83, note: "Cross-season" },
      { name: "Pleated Skirt", score: 75, note: "Resort" },
    ],
  },
  Europe: {
    fabrics: [
      { name: "Italian Wool", score: 93, signal: "Milan capacity" },
      { name: "French Lace", score: 84, signal: "Couture week" },
      { name: "German Loopback", score: 81, signal: "Retail demand" },
      { name: "Portuguese Knit", score: 77, signal: "Sourcing volume" },
    ],
    colors: [
      { name: "Veneto Cream", hex: "#efe6d2", pantone: "12-0710", score: 91 },
      { name: "Milan Grigio", hex: "#6b6b6b", pantone: "17-4015", score: 85 },
      { name: "Provence Lilac", hex: "#a896c4", pantone: "15-3716", score: 76 },
      { name: "Bordeaux", hex: "#5b1a2a", pantone: "19-1726", score: 72 },
    ],
    silhouettes: [
      { name: "Sculpted Blazer", score: 88, note: "FW '26" },
      { name: "Slip Dress", score: 81, note: "Resort" },
      { name: "Long Trench", score: 77, note: "Cross-season" },
    ],
  },
  "United States": {
    fabrics: [
      { name: "Garment-dyed Fleece", score: 91, signal: "Streetwear demand" },
      { name: "Heavyweight Jersey", score: 87, signal: "DTC sell-through" },
      { name: "Recycled Denim", score: 83, signal: "Sustainability filter" },
      { name: "Tech Nylon", score: 75, signal: "Outerwear pipeline" },
    ],
    colors: [
      { name: "Brooklyn Charcoal", hex: "#2b2b2e", pantone: "19-4006", score: 89 },
      { name: "Sun-faded Coral", hex: "#d97757", pantone: "16-1442", score: 84 },
      { name: "Desert Tan", hex: "#c2a07a", pantone: "15-1314", score: 78 },
      { name: "Court Green", hex: "#3a6b4f", pantone: "18-6024", score: 72 },
    ],
    silhouettes: [
      { name: "Relaxed Hoodie", score: 92, note: "All-season" },
      { name: "Cargo Pant", score: 84, note: "FW '26" },
      { name: "Varsity Jacket", score: 78, note: "Drop culture" },
    ],
  },
  India: {
    fabrics: [
      { name: "Khadi Cotton", score: 92, signal: "Handloom revival" },
      { name: "Organic Silk", score: 86, signal: "Export demand" },
      { name: "Linen Blend", score: 80, signal: "Summer collections" },
      { name: "Mulberry Silk", score: 74, signal: "Luxury market" },
    ],
    colors: [
      { name: "Saffron Glow", hex: "#f4c430", pantone: "14-1064", score: 91 },
      { name: "Deep Ochre", hex: "#b37400", pantone: "17-1048", score: 83 },
      { name: "Royal Indigo", hex: "#1e3d59", pantone: "19-4025", score: 80 },
      { name: "Lotus Pink", hex: "#ff7b90", pantone: "15-2216", score: 72 },
    ],
    silhouettes: [
      { name: "Flowing Kurta Cut", score: 88, note: "Contemporary wear" },
      { name: "Relaxed Caftan", score: 82, note: "Resort" },
      { name: "Draped Tunic", score: 79, note: "SS '26" },
    ],
  },
  China: {
    fabrics: [
      { name: "Technical Silk", score: 94, signal: "Hangzhou high-tech mills" },
      { name: "Recycled Polyester", score: 89, signal: "Green manufacturing" },
      { name: "Jacquard Brocade", score: 81, signal: "Cultural fusion trends" },
      { name: "Bamboo Viscose", score: 76, signal: "Sustainable demand" },
    ],
    colors: [
      { name: "Imperial Red", hex: "#b81d24", pantone: "19-1763", score: 93 },
      { name: "Jade Green", hex: "#00a86b", pantone: "16-5421", score: 85 },
      { name: "Shanghai Sumi", hex: "#111111", pantone: "19-4305", score: 82 },
      { name: "Yellow River Gold", hex: "#d4af37", pantone: "15-0955", score: 70 },
    ],
    silhouettes: [
      { name: "Mandarin Collar Shirt", score: 89, note: "Minimalist fashion" },
      { name: "Asymmetrical Dress", score: 83, note: "SS '26" },
      { name: "Wide-sleeve Outerwear", score: 78, note: "FW '26" },
    ],
  },
};

const REGIONS: Region[] = ["Japan", "United Kingdom", "Europe", "United States", "India", "China"];
const SEASONS = ["S/S 26", "F/W 26", "S/S 27"];
export function TrendForecast() {
  const { t } = useLanguage();
  const [region, setRegion] = useState<Region>("Japan");
  const [forecast, setForecast] = useState<Forecast | null>(null);
  const [loading, setLoading] = useState<boolean>(true);

  const fetchForecast = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from("trends")
        .select("fabrics, colors, silhouettes")
        .eq("region", region)
        .order("updated_at", { ascending: false })
        .limit(1)
        .maybeSingle();

      if (error) {
        console.warn("Could not query 'trends' database table:", error.message);
        setForecast(DEFAULT_DATA[region] || null);
      } else if (data) {
        setForecast({
          fabrics: typeof data.fabrics === "string" ? JSON.parse(data.fabrics) : data.fabrics,
          colors: typeof data.colors === "string" ? JSON.parse(data.colors) : data.colors,
          silhouettes: typeof data.silhouettes === "string" ? JSON.parse(data.silhouettes) : data.silhouettes,
        });
      } else {
        setForecast(DEFAULT_DATA[region] || null);
      }
    } catch (err) {
      console.warn("Failed to load forecast:", err);
      setForecast(DEFAULT_DATA[region] || null);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchForecast();
  }, [region]);

  return (
    <section id="trends" className="relative py-32">
      <div className="mx-auto max-w-7xl px-6">
        <div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-8 mb-12">
          <div className="max-w-2xl">
            <p className="text-[10px] uppercase tracking-[0.3em] text-electric mb-6">{t("trendForecast.label")}</p>
            <h2 className="font-serif text-4xl sm:text-6xl tracking-tight text-balance">
              {t("trendForecast.heading")} <span className="italic gradient-text">{t("trendForecast.headingHighlight")}</span>{t("trendForecast.headingEnd")}
            </h2>
            <p className="mt-6 text-muted-foreground">
              {t("trendForecast.description")}
            </p>
          </div>
          
          <div className="flex flex-wrap gap-1.5 p-1 glass rounded-full border border-border">
            {REGIONS.map((r) => (
              <button
                key={r}
                onClick={() => setRegion(r)}
                className={`text-xs px-3.5 py-1.5 rounded-full transition-colors cursor-pointer ${
                  region === r ? "bg-foreground text-background" : "text-muted-foreground hover:text-foreground"
                }`}
              >
                {r}
              </button>
            ))}
          </div>
        </div>

        {loading ? (
          <div className="h-[400px] flex items-center justify-center rounded-3xl border border-white/5 glass bg-white/[0.01]">
            <div className="flex flex-col items-center gap-3">
              <Loader2 className="size-8 animate-spin text-electric" />
              <p className="text-xs text-muted-foreground">{t("trendForecast.loadingText")}</p>
            </div>
          </div>
        ) : forecast ? (
          <div className="grid lg:grid-cols-3 gap-5">
            {/* Fabrics */}
            <Panel title={t("trendForecast.panelFabrics")} icon={Activity}>
              <AnimatePresence mode="wait">
                <motion.div
                  key={region + "-fabrics"}
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -8 }}
                  transition={{ duration: 0.25 }}
                  className="space-y-3"
                >
                  {forecast.fabrics.map((f) => (
                    <div key={f.name} className="space-y-1.5">
                      <div className="flex items-center justify-between text-sm">
                        <span>{f.name}</span>
                        <span className="text-xs text-electric tabular-nums">{f.score}</span>
                      </div>
                      <div className="h-1.5 rounded-full bg-secondary overflow-hidden">
                        <motion.div
                          initial={{ width: 0 }}
                          animate={{ width: `${f.score}%` }}
                          transition={{ duration: 0.7, ease: "easeOut" }}
                          className="h-full rounded-full bg-gradient-to-r from-electric to-violet-glow"
                        />
                      </div>
                      <p className="text-[10px] text-muted-foreground">{f.signal}</p>
                    </div>
                  ))}
                </motion.div>
              </AnimatePresence>
            </Panel>

            {/* Colors */}
            <Panel title={t("trendForecast.panelColors")} icon={Sparkles}>
              <AnimatePresence mode="wait">
                <motion.div
                  key={region + "-colors"}
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -8 }}
                  transition={{ duration: 0.25 }}
                  className="space-y-3"
                >
                  {forecast.colors.map((c) => (
                    <div key={c.name} className="flex items-center gap-3 rounded-xl p-2.5 glass border border-border">
                      <div
                        className="size-10 rounded-lg shrink-0 ring-1 ring-foreground/10"
                        style={{ backgroundColor: c.hex }}
                      />
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center justify-between gap-2">
                          <p className="text-sm truncate">{c.name}</p>
                          <span className="text-xs text-electric tabular-nums">{c.score}</span>
                        </div>
                        <p className="text-[10px] text-muted-foreground">
                          Pantone {c.pantone} · {c.hex.toUpperCase()}
                        </p>
                      </div>
                    </div>
                  ))}
                </motion.div>
              </AnimatePresence>
            </Panel>

            {/* Silhouettes */}
            <Panel title={t("trendForecast.panelSilhouettes")} icon={TrendingUp}>
              <AnimatePresence mode="wait">
                <motion.div
                  key={region + "-silhouettes"}
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -8 }}
                  transition={{ duration: 0.25 }}
                  className="space-y-3"
                >
                  {forecast.silhouettes.map((s) => (
                    <div key={s.name} className="rounded-xl p-3 glass border border-border">
                      <div className="flex items-center justify-between mb-2">
                        <p className="text-sm">{s.name}</p>
                        <span className="text-xs text-electric tabular-nums">{s.score}</span>
                      </div>
                      <div className="h-1 rounded-full bg-secondary overflow-hidden mb-2">
                        <motion.div
                          initial={{ width: 0 }}
                          animate={{ width: `${s.score}%` }}
                          transition={{ duration: 0.7 }}
                          className="h-full rounded-full bg-gradient-to-r from-cyan-glow to-electric"
                        />
                      </div>
                      <p className="text-[10px] text-muted-foreground">{s.note}</p>
                    </div>
                  ))}

                  <div className="mt-4 pt-4 border-t border-border text-[10px] text-muted-foreground flex items-center justify-between">
                    <span>{t("trendForecast.signalsAnalysed")}</span>
                    <span className="tabular-nums text-foreground/80">2.4M / 6h</span>
                  </div>
                </motion.div>
              </AnimatePresence>
            </Panel>
          </div>
        ) : (
          <div className="text-center py-12 text-muted-foreground">{t("trendForecast.noForecast")}</div>
        )}
      </div>
    </section>
  );
}

function Panel({
  title,
  icon: Icon,
  children,
}: {
  title: string;
  icon: React.ComponentType<{ className?: string }>;
  children: React.ReactNode;
}) {
  return (
    <div className="glass-strong rounded-3xl p-5">
      <div className="flex items-center justify-between mb-5">
        <div className="flex items-center gap-2">
          <div className="size-7 rounded-full border border-electric/20 bg-electric/10 flex items-center justify-center">
            <Icon className="size-3.5 text-electric" />
          </div>
          <p className="text-sm">{title}</p>
        </div>
        <span className="text-[9px] uppercase tracking-widest text-muted-foreground">Live</span>
      </div>
      {children}
    </div>
  );
}
