/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as SupplierRequestRouteImport } from './routes/supplier-request'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BlogBlogIdRouteImport } from './routes/blog.$blogId'
import { Route as AdminTrendsRouteImport } from './routes/admin/trends'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as AdminSuppliersRouteImport } from './routes/admin/suppliers'
import { Route as AdminSupplierRequestsRouteImport } from './routes/admin/supplier-requests'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminBlogsRouteImport } from './routes/admin/blogs'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierRequestRoute = SupplierRequestRouteImport.update({
  id: '/supplier-request',
  path: '/supplier-request',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BlogBlogIdRoute = BlogBlogIdRouteImport.update({
  id: '/blog/$blogId',
  path: '/blog/$blogId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrendsRoute = AdminTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupplierRequestsRoute = AdminSupplierRequestsRouteImport.update({
  id: '/supplier-requests',
  path: '/supplier-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/book-demo': typeof BookDemoRoute
  '/compliance': typeof ComplianceRoute
  '/founders': typeof FoundersRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/supplier-request': typeof SupplierRequestRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/supplier-requests': typeof AdminSupplierRequestsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/trends': typeof AdminTrendsRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/book-demo': typeof BookDemoRoute
  '/compliance': typeof ComplianceRoute
  '/founders': typeof FoundersRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/supplier-request': typeof SupplierRequestRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/supplier-requests': typeof AdminSupplierRequestsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/trends': typeof AdminTrendsRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/book-demo': typeof BookDemoRoute
  '/compliance': typeof ComplianceRoute
  '/founders': typeof FoundersRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/supplier-request': typeof SupplierRequestRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/supplier-requests': typeof AdminSupplierRequestsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/trends': typeof AdminTrendsRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/assistant'
    | '/book-demo'
    | '/compliance'
    | '/founders'
    | '/how-we-work'
    | '/privacy'
    | '/supplier-request'
    | '/sustainability'
    | '/terms'
    | '/admin/blogs'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/supplier-requests'
    | '/admin/suppliers'
    | '/admin/testimonials'
    | '/admin/trends'
    | '/blog/$blogId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assistant'
    | '/book-demo'
    | '/compliance'
    | '/founders'
    | '/how-we-work'
    | '/privacy'
    | '/supplier-request'
    | '/sustainability'
    | '/terms'
    | '/admin/blogs'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/supplier-requests'
    | '/admin/suppliers'
    | '/admin/testimonials'
    | '/admin/trends'
    | '/blog/$blogId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/assistant'
    | '/book-demo'
    | '/compliance'
    | '/founders'
    | '/how-we-work'
    | '/privacy'
    | '/supplier-request'
    | '/sustainability'
    | '/terms'
    | '/admin/blogs'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/supplier-requests'
    | '/admin/suppliers'
    | '/admin/testimonials'
    | '/admin/trends'
    | '/blog/$blogId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  BookDemoRoute: typeof BookDemoRoute
  ComplianceRoute: typeof ComplianceRoute
  FoundersRoute: typeof FoundersRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  PrivacyRoute: typeof PrivacyRoute
  SupplierRequestRoute: typeof SupplierRequestRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TermsRoute: typeof TermsRoute
  BlogBlogIdRoute: typeof BlogBlogIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-request': {
      id: '/supplier-request'
      path: '/supplier-request'
      fullPath: '/supplier-request'
      preLoaderRoute: typeof SupplierRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$blogId': {
      id: '/blog/$blogId'
      path: '/blog/$blogId'
      fullPath: '/blog/$blogId'
      preLoaderRoute: typeof BlogBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trends': {
      id: '/admin/trends'
      path: '/trends'
      fullPath: '/admin/trends'
      preLoaderRoute: typeof AdminTrendsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/supplier-requests': {
      id: '/admin/supplier-requests'
      path: '/supplier-requests'
      fullPath: '/admin/supplier-requests'
      preLoaderRoute: typeof AdminSupplierRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSupplierRequestsRoute: typeof AdminSupplierRequestsRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminTrendsRoute: typeof AdminTrendsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogsRoute: AdminBlogsRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSupplierRequestsRoute: AdminSupplierRequestsRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminTrendsRoute: AdminTrendsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AssistantRoute: AssistantRoute,
  BookDemoRoute: BookDemoRoute,
  ComplianceRoute: ComplianceRoute,
  FoundersRoute: FoundersRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  PrivacyRoute: PrivacyRoute,
  SupplierRequestRoute: SupplierRequestRoute,
  SustainabilityRoute: SustainabilityRoute,
  TermsRoute: TermsRoute,
  BlogBlogIdRoute: BlogBlogIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
