/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupplierRequestRouteImport } from './routes/supplier-request'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSuppliersRouteImport } from './routes/admin/suppliers'
import { Route as AdminSupplierRequestsRouteImport } from './routes/admin/supplier-requests'
import { Route as AdminShipmentsRouteImport } from './routes/admin/shipments'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDemoRequestsRouteImport } from './routes/admin/demo-requests'

const SupplierRequestRoute = SupplierRequestRouteImport.update({
  id: '/supplier-request',
  path: '/supplier-request',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupplierRequestsRoute = AdminSupplierRequestsRouteImport.update({
  id: '/supplier-requests',
  path: '/supplier-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShipmentsRoute = AdminShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemoRequestsRoute = AdminDemoRequestsRouteImport.update({
  id: '/demo-requests',
  path: '/demo-requests',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/book-demo': typeof BookDemoRoute
  '/supplier-request': typeof SupplierRequestRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/admin/supplier-requests': typeof AdminSupplierRequestsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/book-demo': typeof BookDemoRoute
  '/supplier-request': typeof SupplierRequestRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/admin/supplier-requests': typeof AdminSupplierRequestsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/book-demo': typeof BookDemoRoute
  '/supplier-request': typeof SupplierRequestRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/admin/supplier-requests': typeof AdminSupplierRequestsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/book-demo'
    | '/supplier-request'
    | '/admin/demo-requests'
    | '/admin/login'
    | '/admin/shipments'
    | '/admin/supplier-requests'
    | '/admin/suppliers'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/book-demo'
    | '/supplier-request'
    | '/admin/demo-requests'
    | '/admin/login'
    | '/admin/shipments'
    | '/admin/supplier-requests'
    | '/admin/suppliers'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/book-demo'
    | '/supplier-request'
    | '/admin/demo-requests'
    | '/admin/login'
    | '/admin/shipments'
    | '/admin/supplier-requests'
    | '/admin/suppliers'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  BookDemoRoute: typeof BookDemoRoute
  SupplierRequestRoute: typeof SupplierRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supplier-request': {
      id: '/supplier-request'
      path: '/supplier-request'
      fullPath: '/supplier-request'
      preLoaderRoute: typeof SupplierRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/supplier-requests': {
      id: '/admin/supplier-requests'
      path: '/supplier-requests'
      fullPath: '/admin/supplier-requests'
      preLoaderRoute: typeof AdminSupplierRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipments': {
      id: '/admin/shipments'
      path: '/shipments'
      fullPath: '/admin/shipments'
      preLoaderRoute: typeof AdminShipmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demo-requests': {
      id: '/admin/demo-requests'
      path: '/demo-requests'
      fullPath: '/admin/demo-requests'
      preLoaderRoute: typeof AdminDemoRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDemoRequestsRoute: typeof AdminDemoRequestsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminShipmentsRoute: typeof AdminShipmentsRoute
  AdminSupplierRequestsRoute: typeof AdminSupplierRequestsRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDemoRequestsRoute: AdminDemoRequestsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminShipmentsRoute: AdminShipmentsRoute,
  AdminSupplierRequestsRoute: AdminSupplierRequestsRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssistantRoute: AssistantRoute,
  BookDemoRoute: BookDemoRoute,
  SupplierRequestRoute: SupplierRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
